### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by kurtkraut** [regit/pshitt#3]
Hello,

This is a clever, lean and fast program to catch malicious botnets. It is indeed a very important tool. Could you kindly port it to python 3 so it can still be used by people? Thanks in advance.

**Comment by regit** [comment]
Hello,

I can try to do that.

Could you paste the error you have with Python 3 ? It will help.

**Comment by regit** [comment]
As from 4020e7ba9c35e47be5bcd263c347bda04f0d745f (just pushed) it should work properly with Python 3. Please confirm or give me information about the error you have.

**Comment by sem-hub** [comment]
I can confirm it works properly with python 3.8.
